-- MySQL Script generated by MySQL Workbench
-- Fri Feb 14 15:45:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema easy-quiz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema easy-quiz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `easy-quiz` DEFAULT CHARACTER SET utf8 ;
USE `easy-quiz` ;

-- -----------------------------------------------------
-- Table `easy-quiz`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easy-quiz`.`answers` (
  `id_answers` INT NOT NULL AUTO_INCREMENT,
  `answer` TEXT(250) NOT NULL,
  `is_correct` TINYINT NOT NULL,
  `id_questions` INT NOT NULL,
  PRIMARY KEY (`id_answers`),
  INDEX `id_questions` (`id_questions` ASC) VISIBLE,
  CONSTRAINT `fk_answers_questions`
    FOREIGN KEY (`id_questions`)
    REFERENCES `easy-quiz`.`questions` (`id_questions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easy-quiz`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easy-quiz`.`questions` (
  `id_questions` INT NOT NULL AUTO_INCREMENT,
  `question` TEXT(250) NOT NULL,
  `type` ENUM('open', 'options', 'multiple') NOT NULL DEFAULT 'open',
  `id_quizes` INT NOT NULL,
  PRIMARY KEY (`id_questions`),
  INDEX `id_quizes` (`id_quizes` ASC) VISIBLE,
  CONSTRAINT `fk_questions_quizes`
    FOREIGN KEY (`id_quizes`)
    REFERENCES `easy-quiz`.`quizes` (`id_quizes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easy-quiz`.`quizes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easy-quiz`.`quizes` (
  `id_quizes` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT(30) NOT NULL,
  `about` TEXT(1000) NULL,
  `id_topics` INT NOT NULL,
  PRIMARY KEY (`id_quizes`),
  INDEX `id_topics` (`id_topics` ASC) VISIBLE,
  CONSTRAINT `fk_quizes_topics`
    FOREIGN KEY (`id_topics`)
    REFERENCES `easy-quiz`.`topics` (`id_topics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easy-quiz`.`topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easy-quiz`.`topics` (
  `id_topics` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT(20) NOT NULL,
  `is_public` TINYINT NOT NULL DEFAULT 0,
  `id_users` INT NOT NULL,
  PRIMARY KEY (`id_topics`),
  INDEX `id_users` (`id_users` ASC) VISIBLE,
  CONSTRAINT `fk_topics_users`
    FOREIGN KEY (`id_users`)
    REFERENCES `easy-quiz`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easy-quiz`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easy-quiz`.`users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_users`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
